export const mockupData = [
  {
    id: 1,
    type: `캠페인/이벤트`,
    category: `campaign`,
    path: `/tidings/campaign`,
    data: [
      {
        id: 1,
        tag: [
          { text: '이벤트', id: 7, mode: 'mode1' },
          { text: '진행중', id: 1, mode: 'mode1' },
        ],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '방학 퀴즈 뽀개기 이벤트1',
        detailTitle: '기특하데이1',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 2,
        tag: [
          { text: '이벤트', id: 7, mode: 'mode1' },
          { text: '종료', id: 3, mode: 'mode1' },
        ],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '방학 퀴즈 뽀개기 이벤트2',
        detailTitle: '기특하데이2',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 3,
        tag: [
          { text: '캠페인', id: 2, mode: 'mode1' },
          { text: '진행중', id: 1, mode: 'mode1' },
        ],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '방학 퀴즈 뽀개기 이벤트3',
        detailTitle: '기특하데이3',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 4,
        tag: [
          { text: '캠페인', id: 2, mode: 'mode1' },
          { text: '종료', id: 3, mode: 'mode1' },
        ],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '방학 퀴즈 뽀개기 이벤트4',
        detailTitle: '기특하데이4',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 5,
        tag: [
          { text: '이벤트', id: 7, mode: 'mode1' },
          { text: '종료', id: 3, mode: 'mode1' },
        ],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '방학 퀴즈 뽀개기 이벤트5',
        detailTitle: '기특하데이5',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 6,
        tag: [
          { text: '이벤트', id: 7, mode: 'mode1' },
          { text: '종료', id: 3, mode: 'mode1' },
        ],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '방학 퀴즈 뽀개기 이벤트6',
        detailTitle: '기특하데이6',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 7,
        tag: [
          { text: '이벤트', id: 7, mode: 'mode1' },
          { text: '진행중', id: 1, mode: 'mode1' },
        ],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '방학 퀴즈 뽀개기 이벤트7',
        detailTitle: '기특하데이7',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 8,
        tag: [
          { text: '이벤트', id: 7, mode: 'mode1' },
          { text: '진행중', id: 1, mode: 'mode1' },
        ],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '방학 퀴즈 뽀개기 이벤트8',
        detailTitle: '기특하데이8',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 9,
        tag: [
          { text: '이벤트', id: 7, mode: 'mode1' },
          { text: '진행중', id: 1, mode: 'mode1' },
        ],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '방학 퀴즈 뽀개기 이벤트9',
        detailTitle: '기특하데이9',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
    ],
  },
  {
    id: 2,
    type: `선교 스토리`,
    category: `mission`,
    path: `/tidings/mission`,
    data: [
      {
        id: 1,
        tag: [{ text: 'CGN 소식', id: 14, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트1',
        detailTitle: '기특하데이1',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 2,
        tag: [{ text: 'CGN 소식', id: 14, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트2',
        detailTitle: '기특하데이2',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 3,
        tag: [{ text: 'CGN 소식', id: 14, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트3',
        detailTitle: '기특하데이3',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 4,
        tag: [{ text: '해외지사', id: 9, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트4',
        detailTitle: '기특하데이4',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 5,
        tag: [{ text: '해외지사', id: 9, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트5',
        detailTitle: '기특하데이5',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 6,
        tag: [{ text: '해외지사', id: 9, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트6',
        detailTitle: '기특하데이6',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 7,
        tag: [{ text: '선교지', id: 5, mode: 'mode1' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트7',
        detailTitle: '기특하데이7',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 8,
        tag: [{ text: '선교지', id: 5, mode: 'mode1' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트8',
        detailTitle: '기특하데이8',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 9,
        tag: [{ text: '선교지', id: 5, mode: 'mode1' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트9',
        detailTitle: '기특하데이9',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 10,
        tag: [{ text: '선교사 기도', id: 4, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트10',
        detailTitle: '기특하데이10',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 11,
        tag: [{ text: '선교사 기도', id: 4, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트11',
        detailTitle: '기특하데이11',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 12,
        tag: [{ text: '선교사 기도', id: 4, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트12',
        detailTitle: '기특하데이12',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 13,
        tag: [{ text: '기타', id: 10, mode: 'mode1' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트13',
        detailTitle: '기특하데이13',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 14,
        tag: [{ text: '기타', id: 10, mode: 'mode1' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트14',
        detailTitle: '기특하데이14',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 15,
        tag: [{ text: '기타', id: 10, mode: 'mode1' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트15',
        detailTitle: '기특하데이15',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
    ],
  },
  {
    id: 3,
    type: `후원 스토리`,
    category: `support`,
    path: `/tidings/support`,
    data: [
      {
        id: 1,
        tag: [{ text: '후원', id: 11, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트1',
        detailTitle: '기특하데이1',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 2,
        tag: [{ text: '후원', id: 11, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트2',
        detailTitle: '기특하데이2',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 3,
        tag: [{ text: '후원', id: 11, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트3',
        detailTitle: '기특하데이3',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 4,
        tag: [{ text: '후원', id: 11, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트4',
        detailTitle: '기특하데이4',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 5,
        tag: [{ text: '후원영상', id: 12, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트5',
        detailTitle: '기특하데이5',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 6,
        tag: [{ text: '후원영상', id: 12, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트6',
        detailTitle: '기특하데이6',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 7,
        tag: [{ text: '후원영상', id: 12, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트7',
        detailTitle: '기특하데이7',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 8,
        tag: [{ text: '후원영상', id: 12, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트8',
        detailTitle: '기특하데이8',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 9,
        tag: [{ text: '후원영상', id: 12, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title: '미션 데이터 테스트9',
        detailTitle: '기특하데이9',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `▶ 1월 1일 공개된  <CGN과 함께 일-일 통독>은 새롭게 론칭한 성경 통독 프로그램입니다. 기존 <하루 20분 공동체 성경읽기>의 업그레이드 버전으로 새로운 삽화와 1인 낭독으로 성경 통독에 대한 흥미를 북돋습니다. 하루 15분이면 1년 1독을 완성하도록 구성했죠. 특히 아름답고 풍성한 삽화로 눈과 귀가 즐거운 성경읽기를 할 수 있답니다. 현재 CGN TV를 통해 방송되고 있으며, 퐁당과 유튜브에도 매일 업로드됩니다. (tip! OTT '퐁당'에서 시청하면 자동 진도체크가 되어 편리하게 통독할 수 있답니다.)`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
    ],
  },
  {
    id: 4,
    type: `보도 자료`,
    category: `broadcast`,
    path: `/tidings/broadcast`,
    data: [
      {
        id: 1,
        tag: [{ text: '보도 자료', id: 13, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title:
          'english test 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트',
        detailTitle: '기특하데이1',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `2022년 9월 첫선을 보인 이후 책을 사랑하는 시청자들에게 큰 사랑을 받은 <잇쉬의 서재>가 독서의 계절에 선물처럼 ‘시즌2’로 돌아왔습니다. 시즌 2에서도 세 명의 텔러가 기독 저자들의 ‘저서’와 ‘저자들의 삶’을 흥미롭게 들려줄 텐데요. 그중 첫 번째 텔러로 출연한 배우 한혜진을 만났습니다. 첫 촬영을 마친 그녀에게 <잇쉬의 서재 시즌2>는 어떻게 다가왔을까요?`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 2,
        tag: [{ text: '보도 자료', id: 13, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title:
          '보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트2',
        detailTitle: '기특하데이2',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `2022년 9월 첫선을 보인 이후 책을 사랑하는 시청자들에게 큰 사랑을 받은 <잇쉬의 서재>가 독서의 계절에 선물처럼 ‘시즌2’로 돌아왔습니다. 시즌 2에서도 세 명의 텔러가 기독 저자들의 ‘저서’와 ‘저자들의 삶’을 흥미롭게 들려줄 텐데요. 그중 첫 번째 텔러로 출연한 배우 한혜진을 만났습니다. 첫 촬영을 마친 그녀에게 <잇쉬의 서재 시즌2>는 어떻게 다가왔을까요?`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 3,
        tag: [{ text: '보도 자료', id: 13, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title:
          '보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트3',
        detailTitle: '기특하데이3',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `2022년 9월 첫선을 보인 이후 책을 사랑하는 시청자들에게 큰 사랑을 받은 <잇쉬의 서재>가 독서의 계절에 선물처럼 ‘시즌2’로 돌아왔습니다. 시즌 2에서도 세 명의 텔러가 기독 저자들의 ‘저서’와 ‘저자들의 삶’을 흥미롭게 들려줄 텐데요. 그중 첫 번째 텔러로 출연한 배우 한혜진을 만났습니다. 첫 촬영을 마친 그녀에게 <잇쉬의 서재 시즌2>는 어떻게 다가왔을까요?`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 4,
        tag: [{ text: '보도 자료', id: 13, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title:
          '보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트4',
        detailTitle: '기특하데이4',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `2022년 9월 첫선을 보인 이후 책을 사랑하는 시청자들에게 큰 사랑을 받은 <잇쉬의 서재>가 독서의 계절에 선물처럼 ‘시즌2’로 돌아왔습니다. 시즌 2에서도 세 명의 텔러가 기독 저자들의 ‘저서’와 ‘저자들의 삶’을 흥미롭게 들려줄 텐데요. 그중 첫 번째 텔러로 출연한 배우 한혜진을 만났습니다. 첫 촬영을 마친 그녀에게 <잇쉬의 서재 시즌2>는 어떻게 다가왔을까요?`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 5,
        tag: [{ text: '보도 자료', id: 13, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title:
          '보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트5',
        detailTitle: '기특하데이5',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `2022년 9월 첫선을 보인 이후 책을 사랑하는 시청자들에게 큰 사랑을 받은 <잇쉬의 서재>가 독서의 계절에 선물처럼 ‘시즌2’로 돌아왔습니다. 시즌 2에서도 세 명의 텔러가 기독 저자들의 ‘저서’와 ‘저자들의 삶’을 흥미롭게 들려줄 텐데요. 그중 첫 번째 텔러로 출연한 배우 한혜진을 만났습니다. 첫 촬영을 마친 그녀에게 <잇쉬의 서재 시즌2>는 어떻게 다가왔을까요?`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 6,
        tag: [{ text: '보도 자료', id: 13, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title:
          '보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트6',
        detailTitle: '기특하데이6',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `2022년 9월 첫선을 보인 이후 책을 사랑하는 시청자들에게 큰 사랑을 받은 <잇쉬의 서재>가 독서의 계절에 선물처럼 ‘시즌2’로 돌아왔습니다. 시즌 2에서도 세 명의 텔러가 기독 저자들의 ‘저서’와 ‘저자들의 삶’을 흥미롭게 들려줄 텐데요. 그중 첫 번째 텔러로 출연한 배우 한혜진을 만났습니다. 첫 촬영을 마친 그녀에게 <잇쉬의 서재 시즌2>는 어떻게 다가왔을까요?`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 7,
        tag: [{ text: '보도 자료', id: 13, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title:
          '보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트7',
        detailTitle: '기특하데이7',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `2022년 9월 첫선을 보인 이후 책을 사랑하는 시청자들에게 큰 사랑을 받은 <잇쉬의 서재>가 독서의 계절에 선물처럼 ‘시즌2’로 돌아왔습니다. 시즌 2에서도 세 명의 텔러가 기독 저자들의 ‘저서’와 ‘저자들의 삶’을 흥미롭게 들려줄 텐데요. 그중 첫 번째 텔러로 출연한 배우 한혜진을 만났습니다. 첫 촬영을 마친 그녀에게 <잇쉬의 서재 시즌2>는 어떻게 다가왔을까요?`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 8,
        tag: [{ text: '보도 자료', id: 13, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title:
          '보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트8',
        detailTitle: '기특하데이8',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `2022년 9월 첫선을 보인 이후 책을 사랑하는 시청자들에게 큰 사랑을 받은 <잇쉬의 서재>가 독서의 계절에 선물처럼 ‘시즌2’로 돌아왔습니다. 시즌 2에서도 세 명의 텔러가 기독 저자들의 ‘저서’와 ‘저자들의 삶’을 흥미롭게 들려줄 텐데요. 그중 첫 번째 텔러로 출연한 배우 한혜진을 만났습니다. 첫 촬영을 마친 그녀에게 <잇쉬의 서재 시즌2>는 어떻게 다가왔을까요?`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
      {
        id: 9,
        tag: [{ text: '보도 자료', id: 13, mode: 'mode2' }],
        src: `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_small.png`,
        contentSrc: [
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
          `${import.meta.env.VITE_PUBLIC_URL}images/tidings/card_content_big.png`,
        ],
        title:
          '보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트 보도 데이터 테스트9',
        detailTitle: '기특하데이9',
        subTitle: '1. 다양한 신규 콘텐츠 공개',
        content: `2022년 9월 첫선을 보인 이후 책을 사랑하는 시청자들에게 큰 사랑을 받은 <잇쉬의 서재>가 독서의 계절에 선물처럼 ‘시즌2’로 돌아왔습니다. 시즌 2에서도 세 명의 텔러가 기독 저자들의 ‘저서’와 ‘저자들의 삶’을 흥미롭게 들려줄 텐데요. 그중 첫 번째 텔러로 출연한 배우 한혜진을 만났습니다. 첫 촬영을 마친 그녀에게 <잇쉬의 서재 시즌2>는 어떻게 다가왔을까요?`,
        startDate: '2022-01-01',
        endDate: '2024.11.05',
      },
    ],
  },
];

export const paymentMockupData = [
  {
    id: 0,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/bg/main_first_section_bg.png`,
    title: `세상에 없는 가치와`,
    depthTitle: `감동을 담다`,
    subTitle: `CGN이 세상에 없는 가치와 감동을 전합니다.`,
  },
  {
    id: 1,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/bg/main_first_section_bg.png`,
    title: `세상에 없는 가치와`,
    depthTitle: `감동을 담다`,
    subTitle: `CGN이 세상에 없는 가치와 감동을 전합니다.`,
  },
  {
    id: 2,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/bg/main_first_section_bg.png`,
    title: `세상에 없는 가치와`,
    depthTitle: `감동을 담다`,
    subTitle: `CGN이 세상에 없는 가치와 감동을 전합니다.`,
  },
  {
    id: 3,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/bg/main_first_section_bg.png`,
    title: `세상에 없는 가치와`,
    depthTitle: `감동을 담다`,
    subTitle: `CGN이 세상에 없는 가치와 감동을 전합니다.`,
  },
];

export const mediaData = [
  {
    id: 0,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 1,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 2,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 3,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 4,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 5,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 6,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
  {
    id: 7,
    src: `${import.meta.env.VITE_PUBLIC_URL}images/home/media_data.png`,
    title: `휴먼네컷`,
    subtitle: `오리지널`,
  },
];
